openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /api/admin/tokens/:
    get:
      summary: 管理员：查看token列表
      deprecated: false
      description: |-
        查询当前有效的token
        > 注意：无法通过此方式查询token原文（raw）
      tags:
        - admin
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                  status:
                    type: string
                    title: 请求状态
                  total:
                    type: integer
                    title: 总计有效数
                  tokens:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          title: token id
                        sha256Hash:
                          type: string
                          title: token摘要
                        createTime:
                          type: string
                          title: 创建时间
                        creatorIp:
                          type: string
                          title: 创建者ip
                        validUntil:
                          type: string
                          title: 有效期至
                          description: null长期
                          nullable: true
                        whitelistIps:
                          type: array
                          items:
                            type: string
                          title: 白名单ip
                          description: ip/cidr
                          nullable: true
                        lastCallTime:
                          type: string
                          title: 上次使用时间
                          nullable: true
                      required:
                        - id
                      x-apifox-orders:
                        - id
                        - sha256Hash
                        - createTime
                        - creatorIp
                        - validUntil
                        - whitelistIps
                        - lastCallTime
                    title: 有效列表
                    nullable: true
                required:
                  - code
                  - status
                  - total
                x-apifox-orders:
                  - code
                  - status
                  - total
                  - tokens
              example:
                code: 200
                status: success
                total: 2
                tokens:
                  - id: 1
                    sha256hash: >-
                      50fe822a90fdd7f5cb7718dc87ec0547fa5cc8bda0016479d73171c5d66a5af2
                    create_time: '2026-07-18T12:49:55'
                    creator_ip: 127.0.0.1
                    valid_until: '2026-12-31T23:59:59'
                    whitelist_ips:
                      - 10.0.0.0/8
                      - 192.168.1.10
                    last_call_time: null
                  - id: 2
                    sha256hash: >-
                      4c5dc9b7708905f77f5e5d16316b5dfb425e68cb326dcd55a860e90a7707031e
                    create_time: '2026-07-18T12:49:55'
                    creator_ip: 127.0.0.1
                    valid_until: null
                    whitelist_ips: []
                    last_call_time: '2026-07-18T12:59:08'
          headers: {}
          x-apifox-name: 成功
        '400':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                    x-apifox-mock: '{{$number.int}}'
                  status:
                    type: string
                    x-apifox-mock: '{{$string.alpha}}'
                    title: 请求状态
                  message:
                    type: string
                    title: 详细信息
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              examples:
                '3':
                  summary: 传入数据校验失败
                  value:
                    code: 400
                    status: fali
                    message: 字"一"不在候选字中
                '4':
                  summary: 游戏不存在
                  value:
                    code: 400
                    status: fail
                    message: 游戏不存在
                '5':
                  summary: 游戏状态不符合要求
                  value:
                    code: 400
                    status: fail
                    message: 本局游戏已结束,状态不为playing
          headers: {}
          x-apifox-name: 请求内容未预期
        '401':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                    description: http标准响应代码
                    x-apifox-mock: '{{$number.int}}'
                  status:
                    type: string
                    title: 请求状态
                    x-apifox-mock: '{{$string.alpha}}'
                  message:
                    type: string
                    title: 详细信息
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              example:
                code: 401
                status: fail
                message: 缺少Authorization请求头
          headers: {}
          x-apifox-name: 未认证
        '403':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                    x-apifox-mock: '{{$number.int}}'
                  status:
                    type: string
                    title: 请求状态
                    x-apifox-mock: '{{$string.alpha}}'
                  message:
                    type: string
                    title: 详细信息
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              example:
                code: 403
                status: fail
                message: not admin
          headers: {}
          x-apifox-name: 无权限
        '405':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                  message:
                    type: string
                    title: 详细信息
                  status:
                    type: string
                    title: 请求状态
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              example:
                code: 405
                status: fail
                message: Method Not Allowed
          headers: {}
          x-apifox-name: 方法不许可
        '422':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                  status:
                    type: string
                    title: 请求状态
                  message:
                    type: string
                    title: 详细信息
                x-apifox-orders:
                  - code
                  - status
                  - message
                required:
                  - code
                  - status
              example:
                code: 422
                status: fail
                message: guess 参数非法：Value error, 必须输入4字成语
          headers: {}
          x-apifox-name: 请求体有误
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    title: httpCode
                  status:
                    type: string
                    title: 请求状态
                  message:
                    type: string
                    title: 详细信息
                required:
                  - code
                  - status
                x-apifox-orders:
                  - code
                  - status
                  - message
              example:
                code: 500
                status: fail
                message: 服务器内部异常，请稍后重试
          headers: {}
          x-apifox-name: 内部错误
      security:
        - 管理员token验证: []
          x-apifox:
            required: true
            schemeGroups:
              - id: fJmc1TgVDD5EsBaHDgvkl
                schemeIds:
                  - 管理员token验证
            use:
              id: fJmc1TgVDD5EsBaHDgvkl
      x-apifox-folder: admin
      x-apifox-status: testing
      x-run-in-apifox: https://app.apifox.com/web/project/8546191/apis/api-489125753-run
components:
  schemas: {}
  securitySchemes:
    普通token鉴权:
      type: bearer
      scheme: bearer
    管理员token验证:
      type: bearer
      scheme: bearer
servers:
  - url: http://127.0.0.1:8000
    description: 测试环境
security: []